language: node_js

sudo: false

cache: yarn

install:
  - yarn install

jobs:
  include:
    - stage: inspector view
      script: yarn build:inspectorView
    - stage: edit mode
      script: yarn build:editMode

