Yoast:
  YoastSeoForNeos:
    devMode: false
    defaultContentLocale: en-US
    languageToLocaleMapping:
      da: 'da_DK'
      de: 'de_DE-formal'
      en: ''
      es: 'es_ES'
      fi: 'fi'
      fr: 'fr_FR'
      km: ''
      lv: ''
      nl: 'nl_NL-formal'
      no: 'nb_NO'
      pl: 'pl_PL'
      pt-BR: 'pt_BR'
      ru: 'ru_RU'
      zh-CN: 'zh_CN'

Neos:
  Neos:
    userInterface:
      editPreviewModes:
        yoastSeoView:
          isEditingMode: true
          isPreviewMode: false
          fusionRenderingPath: yoastSeoView
          title: 'Yoast.YoastSeoForNeos:Main:editPreviewModes.yoastSeoView'
          position: 'after inPlace'

      translation:
        autoInclude:
          Yoast.YoastSeoForNeos:
            - 'Main'
            - 'NodeTypes/*'
            - 'NodeTypes/Mixin/*'

    fusion:
      autoInclude:
        Yoast.YoastSeoForNeos: true

    Ui:
      resources:
        javascript:
          Yoast.YoastSeoForNeos:YoastInfoView:
            resource: 'resource://Yoast.YoastSeoForNeos/Public/YoastInfoView/Plugin.js'
        stylesheets:
          Yoast.YoastSeoForNeos:YoastInfoView:
            resource: 'resource://Yoast.YoastSeoForNeos/Public/YoastInfoView/Plugin.css'

      frontendConfiguration:
        'Yoast.YoastSeoForNeos':
          contentSelector: 'body'

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Yoast.YoastSeoForNeos:DataSources':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Yoast\YoastSeoForNeos\Controller\.*'
    mvc:
      routes:
        'Yoast.YoastSeoForNeos':
          position: 'before Neos.Neos'
